- name: create an instance
  ec2:
    key_name: my_key
    instance_type: t2.micro
    image: ami-0eb89db7593b5d434
    region: eu-west-2
    wait: true
    instance_tags:
      Name: dockerami
  register: ec2

- name: Add public IP to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: ec2hosts
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to be available
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  loop: "{{ ec2.instances }}"
